### ISSUE TITLE
neo4j-community packages should depened on JDK7

### ISSUE THREAD

**Issue by glennsarti** [glennsarti/neo4j-community-chocolatey#6]
Waiting on a suitable JDK7 package to be available in chocolatey

See https://groups.google.com/forum/#!topic/chocolatey/a7XE9jbBdwU

**Comment by neutmute** [comment]
Looks like the JDK package detects if Java is installed and returns now?

https://github.com/digitaldrummerj-chocolatey/ChocolateyPackages/blob/master/JDK7/tools/chocolateyInstall.ps1#L13

**Comment by glennsarti** [comment]
The ongoing packages now install a private jre so this no longer an issue.
