### ISSUE TITLE
latest nuspec?

### ISSUE THREAD

**Issue by neutmute** [glennsarti/neo4j-community-chocolatey#8]
Hi Glenn - The package definition for the latest neo4jcommunity ([Neo4j Community Edition 2.3.0.20151026](https://chocolatey.org/packages/neo4j-community)) doesn't seem to be in this repo?

Is it in another repo or just missing from here?

**Comment by glennsarti** [comment]
@neutmute Oh dear :-(   I have a feeling I didn't push it up.  I've moved country so I finally have my old computer back.  I'll go through my source and push it up.  If not, I can reverse engineer the package from the gallery.

**Comment by glennsarti** [comment]
Pushed up my changes

**Comment by neutmute** [comment]
:+1:
